-- SQL Script to run in Supabase SQL Editor to match the Carta local SQLite database

-- Stores Table
create table public.stores (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  phone text,
  created_at timestamp with time zone not null default now()
);

-- Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.stores(id) on delete cascade,
  name text not null,
  description text
);

-- Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.stores(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  name text not null,
  brand text not null,
  barcode text,
  quantity integer not null default 0,
  restock_threshold integer not null default 10,
  price double precision not null default 0.0,
  verified integer not null default 0,
  last_updated timestamp with time zone not null default now(),
  supplier text,
  last_delivery_date timestamp with time zone,
  low_stock_flagged integer not null default 0,
  reorder_interval_days integer not null default 7
);

-- Purchase Orders Table
create table public.purchase_orders (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.stores(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  product_name text not null,
  supplier text not null,
  quantity integer not null,
  order_date timestamp with time zone not null,
  delivery_date timestamp with time zone,
  delivered integer not null default 0,
  notes text
);

-- Enable Row Level Security (RLS) - Basic open policy for prototyping functionality
alter table stores enable row level security;
alter table categories enable row level security;
alter table products enable row level security;
alter table purchase_orders enable row level security;

create policy "Enable all access for prototyping stores" on stores for all using (true);
create policy "Enable all access for prototyping categories" on categories for all using (true);
create policy "Enable all access for prototyping products" on products for all using (true);
create policy "Enable all access for prototyping purchase_orders" on purchase_orders for all using (true);
